sudo: false
language: node_js
node_js:
    - "8"
    - "10"
env:
    global:
        - CC_TEST_REPORTER_ID=325f2fef181d2b41dfd850b751d40140d68170490d15d73d372e28b086b7c15f
cache:
    yarn: true
    directories:
        - node_modules

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
script:
    - yarn run build

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
