---


services:
  api_db:
    container_name: 'geo-api-db'
    image: 'postgres:16'
    restart: unless-stopped
    tty: true
    ports:
      - '5432:5432'
    environment:
      - "POSTGRES_USER=${API_DB_USER}"
      - "POSTGRES_PASSWORD=${API_DB_PASSWORD}"
      - "POSTGRES_DB=${API_DB_DATABASE}"
      - "POSTGRES_PORT=${API_DB_PORT}"
    volumes:
      - './config/postgres/api/:/var/lib/pgsql/data'