name: build
on:
  push:
    branches:
      - master
jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ''
          POSTGRES_DB: geofind
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '15'
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn workspace @geofind/api build
      - run: pg_restore --dbname geofind --host=127.0.0.1 --port=5432 --username=postgres ./config/dumps/db.dump
      - uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 67126294d2dca1578a26d1d9d843edcb99e8bb1c78d729e7f5887254475f077b
          NODE_ENV: production
          PORT: 3000
          DB_USER: postgres
          DB_PASSWORD: root
          DB_PORT: 5432
          DB_DATABASE: geofind
          DB_HOST: 127.0.0.1
        with:
          coverageCommand: yarn workspace @geofind/api coverage

